### ISSUE TITLE
Use type property for themes

### ISSUE THREAD

**Issue by usernamehw** [rainglow/vscode#1]
All your themes default to dark. It affects many colors for elements.
```json
"type": "light" | "dark"
```
In addition from 1.19 themes grouped in theme picker (`dark` | `light` | `high contrast`):
![theme-picker](https://user-images.githubusercontent.com/9638156/33919627-bca5ec04-dfca-11e7-8b72-5528ea5bec4e.png)

**Comment by daylerees** [comment]
Ah interesting! Is that an early release build? I'm on the latest and it seems to be `1.18.x`. I'll have a play with this! Should be an easy fix. Thanks for helping! ❤️

**Comment by usernamehw** [comment]
Yep, [Insiders](https://code.visualstudio.com/insiders/) build.

**Comment by daylerees** [comment]
Thanks for the tip @usernamehw! :) I've updated the themes with the light/dark in the `1.0.1` release I've pushed to the marketplace.
