### ISSUE TITLE
Slime Theme's pop up info bar colors are not clear.

### ISSUE THREAD

**Issue by MohamedCharaf** [rainglow/vscode#10]
![rainglowissue](https://user-images.githubusercontent.com/15888823/34458483-40d87012-eddd-11e7-904d-2a8c0647e8a4.PNG)

Buttons to the right of the pop up info bar are not clear. 
Background is light yellow and text color is white.

**Comment by daylerees** [comment]
No problem. I'll fix this tomorrow. :)

**Comment by daylerees** [comment]
Hi there! Sorry for the wait. NYE got in the way. If you update to `1.4.2` you'll find your buttons are now more friendly to the eye. :) Thanks for reporting it!

**Comment by MohamedCharaf** [comment]
Thanks for the great work :) keep it up.
