### ISSUE TITLE
Comparable Brogrammer Theme

### ISSUE THREAD

**Issue by Flaires** [rainglow/vscode#11]
Hey, first of all thanks for you're great work. I love you're themes. But i miss some sort of Brogrammer style theme for the editor. Brogrammer exist in atom for example, but it doesn't seem to update by the maintainer anymore. So my question is, would you like to create some sort of Brogrammer theme in you're style ? :)

For [VSCode](https://marketplace.visualstudio.com/items?itemName=gerane.Theme-Brogrammer) 
For [Atom](https://atom.io/themes/brogrammer-syntax)
Intellij doesn't exist unfortunately

Have a great day !
Best regards

**Comment by daylerees** [comment]
Hi buddy! Let me think about this one. I like my themes to be original, so I need to think if I can live with myself if I were to borrow colours from this one!

**Comment by Flaires** [comment]
@daylerees I fully understand you. I will respect your decision. Thanks, that you take time for this!

**Comment by daylerees** [comment]
Thanks for understanding :) I'm going to close this for now, but it's there in the issue backlog when I decide to make more themes. Have a great day!
