### ISSUE TITLE
Change highlight folder color?

### ISSUE THREAD

**Issue by kkashou** [rainglow/vscode#12]
Hello,

Is there a way to change the pink highlight color on the folder tree structure section whenever a user clicks on the folder to expand what is inside? 

Thanks

**Comment by daylerees** [comment]
Yep absolutely. I'll paste some code later that will let you custom override it. 👍  Stuck in work at the moment.

**Comment by kkashou** [comment]
Awesome thank you :)

**Comment by daylerees** [comment]
Sorry for the wait buddy, but this will get you going.

```json
    "workbench.colorCustomizations": {
        "list.activeSelectionForeground": "#ffffff",
        "list.activeSelectionBackground": "#000000"
    },
```

Add this to your settings and change the colors. It will override it for your editor. :)

**Comment by kkashou** [comment]
Thank you very much :)
