### ISSUE TITLE
Rainglow is broken with short syntax React Fragments

### ISSUE THREAD

**Issue by cedricdelpoux** [rainglow/vscode#26]
Hello, I have a lot [short syntax React fragments](https://reactjs.org/docs/fragments.html#short-syntax) in my codebase. Every theme is broken

# **editor/software** are you using?
VSCode

# **Which theme** are you using?
Joker but the problem is present on each theme

# **Have you tested** the issue with **other themes**?
Yes, the problem is present on each theme

# **Which version** of Rainglow do you have installed?
1.5.2

# Can you **provide screenshots** to highlight the issue?

## With **short** syntax React fragment 
![screenshot 2019-01-22 at 17 13 41](https://user-images.githubusercontent.com/2683300/51548685-1ee16c80-1e69-11e9-90c0-9a80a0f30a18.png)

## With **long** syntax React fragment 
![screenshot 2019-01-22 at 17 14 41](https://user-images.githubusercontent.com/2683300/51548746-3a4c7780-1e69-11e9-9dcd-976986da8b5a.png)

**Comment by daylerees** [comment]
Hi @xuopled ! The new react fragment syntax is awesome, but I think some of the React syntax highlighters don't fully support this yet. So it's more down to them updating, rather than the scheme itself I'm afraid! Hopefully, it will come soon!

**Comment by cedricdelpoux** [comment]
You are right ! It's a syntax highlighter that broked my theme.

Thank you !
