### ISSUE TITLE
Consider using "extensionButton.prominentBackground"

### ISSUE THREAD

**Issue by usernamehw** [rainglow/vscode#5]
Buttons and badges in extension view has green color that doesn't go together with most of the themes:
![extension_prominent_background](https://user-images.githubusercontent.com/9638156/34150074-575dc306-e4b8-11e7-81e0-ccfb9fae8dd1.png)

It would be nice to use it in themes (not necessarily the same color as badges and input focus, just something that's not stands out in theme context).

**Comment by daylerees** [comment]
I did take a look at this and wasn't sure if keeping the green uniform might be better. Maybe I'll try pushing a build with the button as focus color and see if anyone complains. :) - Will keep this issue as a to do for tonight. Thanks again bud!

**Comment by daylerees** [comment]
Oh hey. Where did the settings santa hat come from? 😂

**Comment by usernamehw** [comment]
Insider build is closer to holidays than stable build 🎉

**Comment by daylerees** [comment]
Have added to 1.1.1, thanks mate. :)
