### ISSUE TITLE
QuickOpen placeholder text in Warlock Contrast is hard to read

### ISSUE THREAD

**Issue by mgasparel** [rainglow/vscode#8]
The placeholder text in the Warlock Contrast theme is really hard to read. Take a look at the screenshot below.

![image](https://user-images.githubusercontent.com/2152222/34311780-a6b5e42a-e72d-11e7-87eb-83f0d2aaab10.png)

This is just a nitpick on an otherwise awesome theme!

**Comment by daylerees** [comment]
Ah you're right. That is kinda poop. I'll fix that tomorrow. Thanks. :)

**Comment by daylerees** [comment]
Christmas got in the way. :) Will take a look this evening!

**Comment by daylerees** [comment]
This should be improved in the latest version. Thanks. :)
