### ISSUE TITLE
Reminder: Fix the picker highlight row color.

### ISSUE THREAD

**Issue by daylerees** [rainglow/vscode#9]
http://dayle.io/ELLOvg

@usernamehw do you have any idea what value determines the background of the current row in the picker, as seen above?

The build in themes seem to have it styled, but I can't seem to find it!

Thanks! :)

**Comment by usernamehw** [comment]
"list.focusBackground": "#ff6a00",

**Comment by daylerees** [comment]
That's awesome, thanks man! Do you have a twitter handle? I'd love to give you a shout out on there for all the help you've given.

**Comment by usernamehw** [comment]
I'm not on twitter.

**Comment by usernamehw** [comment]
So, this is a build. If a ever want to contribute where is the pointer (or always better to create an issue first?).

And do these themes strive to match some original or do they vary from editor to editor?

**Comment by daylerees** [comment]
Always better to create an issue. The generator is very custom and lacks any docs for now. :) Normally I try to get it as close to VSCODE as possible, but lots of editors have more simple rendering so it's not possible. In that circumstance I just give it the best 'feel' for the themes while still making sense for the editor's languages.
